config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

  get 'another_page' => 'welcome#another_page'
  get 'interesting_fact' => 'welcome#interesting_fact'
  get 'something_page' => 'welcome#something_page'
  get 'please_click_me' => 'welcome#please_click_me'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(name: data["name"], first_name: data["first_name"], last_name: data["last_name"], email: data["email"], password: Devise.friendly_token[0,20])
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2

    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def another_page

  end

  def interesting_fact

  end

  def something_page

  end

  def please_click_me

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else flash_type.to_s
      end
   end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Skeleton</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render partial: "shared/flash_messages", flash: flash %>
		<%= render partial: "shared/navbar" %>
		<div class="container">
			<%= render partial: "shared/header" %>
			<div class=""row">
				<div class="col-sm-8 blog-main">
					<%= yield %>
				</div>
				<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
					<div class="sidebar-module sidebar-module-inset">
						<%= render partial: "shared/about" %>
					</div>
					<div class="sidebar-module">
						<%= render partial: "shared/another_sidebar" %>
					</div>
					<div class="sidebar-module">
						<%= render partial: "shared/links_sidebar" %>
					</div>
				</div>
			</div>
		</div>
		<%= render partial: "shared/footer" %>
	</body>
</html>

app/views/shared/_about.html.erb
<h4>About</h4>
<p>Add some info about you, the site, anything that you want. Add some links, words, whatever.</p>

app/views/shared/_another_sidebar.html.erb
<h4>Another sidebar</h4>
<p>Maybe you need some more info here about some stuff. Perhaps a <%= link_to "link", another_page_url -%> to another page. Or what about a list of other interesting things.</p>
<ol class="list-unstyled">
	<li><%= link_to "An interesting fact", interesting_fact_url %></li>
	<li><%= link_to "A page about something", something_page_url %></li>
	<li><%= link_to "Please click me", please_click_me_url %></li>
</ol>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="blog-footer">
	<p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>. <em>Rails-i-fied</em> by <a href="https://twitter.com/travellingbard">@travellingbard</a>.</p>
</div>

app/views/shared/_header.html.erb
<div class="blog-header">
	<h1 class="blog-title">Skeleton</h1>
	<p class="lead blog-description">Rails 4.1 web application with devise, oauth, bootstrap and more</p>
</div>

app/views/shared/_links_sidebar.html.erb
<h4>Elsewhere</h4>
<ol class="list-unstyled">
	<li><a href="https://github.com/ianwdunlop">GitHub</a></li>
	<li><a href="https://twitter.com/travellingbard">Twitter</a></li>
</ol>

app/views/shared/_navbar.html.erb
<div class="blog-masthead">
	<div class="container">
		<nav class="blog-nav">
		<%= link_to "Home", root_url, class: "blog-nav-item #{current_page?(controller: 'welcome', action: 'index') ? 'active' : ''}" %>
		<%= link_to "Facts", interesting_fact_url, class: "blog-nav-item #{current_page?(controller: 'welcome', action: 'interesting_fact') ? 'active' : ''}" %>
		<%= link_to "Something", something_page_url, class: "blog-nav-item #{current_page?(controller: 'welcome', action: 'something_page') ? 'active' : ''}" %>
		<%= link_to "Click here", please_click_me_url, class: "blog-nav-item #{current_page?(controller: 'welcome', action: 'please_click_me') ? 'active' : ''}" %>
		<ul class="nav navbar-nav navbar-right"><% if !user_signed_in? %>
				<li class="medium-padding" id="sign-in-text">Sign in with</li>
				<li>
				<%= link_to user_omniauth_authorize_url(:google_oauth2), class: "btn btn-social-icon btn-google-plus skeleton-text-top" do %>
					<i class="fa fa-google-plus"></i>
				<% end %>
				</li>
				<li class="medium-padding" id="sign-in-text">or</li>
				<li><div class="btn-group">
					<%= link_to "Sign in", new_user_session_url, class: "btn btn-default" %>
					<%= link_to "Register", new_user_registration_url, class: "btn btn-default" %>
				</div>
				</li>
			<% else %>
				<%= link_to "Log out", destroy_user_session_url, class: "blog-nav-item", method: 'delete' %>
			<% end %>
		</ul>
		</nav>
	</div>
</div>

app/views/welcome/another_page.html.erb
<h3>And another thing...</h3>
<p>Really, another page with not a lot of content. Come on, that's just lazy.</p>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<p>Welcome <%= current_user.first_name %>. It's great to see you here. What have you been doing recently?</p>
<% else %>
	<p>Hello and welcome to this great website. Why not login or register using the buttons at the top right. Or just cruise round some content.</p>
<% end %>

app/views/welcome/interesting_fact.html.erb
<h3>An interesting fact</h3>
<p>The loudest land animal is the Howler monkey whose deep growls and howls in the forest can travel clearly up to 3 miles. So there.</p>

app/views/welcome/please_click_me.html.erb
<h3>You clicked me</h3>
<p>You know you shouldn't always do what people tell you. In this case it was ok though. Thanks for clicking.</p>

app/views/welcome/something_page.html.erb
<h3>Something</h3>
<p>There should be something on this page but I couldn't think of anything. I'm sure you could do better.</p>